# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1307911598);
user_pref("app.update.lastUpdateTime.background-update-timer", 1307911598);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1307911598);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1307911598);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1307911598);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 640000);
user_pref("browser.migration.version", 5);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.startup.homepage", "http://127.0.0.1/HTTP-RUN/$mpd");
user_pref("browser.startup.homepage_override.buildID", "20110413222027");
user_pref("browser.startup.homepage_override.mstone", "rv:2.0.1");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 3);
user_pref("extensions.enabledAddons", "webrunner@salsitasoft.com:4.0.1,{972ce4c6-7e08-4474-a285-3208198ce6fd}:4.0.1");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/opt/firefox/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1307458748000}}},{\"name\":\"app-profile\",\"addons\":{\"webrunner@salsitasoft.com\":{\"descriptor\":\"/home/mz/.webapps/mpd.control@webrunner.app/profile/extensions/webrunner@salsitasoft.com\",\"mtime\":1307911392000}}}]");
user_pref("extensions.lastAppVersion", "4.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 62946);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.migrated", true);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1310503402);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
